### ISSUE TITLE
Question about collab

### ISSUE THREAD

**Issue by AHEADer** [benjaminheng/dotfiles#1]
Hi Benjamin, 

I'm Junda now working on collab(My id: AHEADer) and I've met some problems about the testing part, I cannot pass the e2e test now. I'm new to javascript and I have these two questions:

1. How to config for the e2e test. For I have to use Google account to login and Cristina has let me join the google developer console. I've got credentials for this project, containing client_id and client_secret. Is it enough to login? I've noticed codes (/asserts/app/test_e2e/page_objects/login.js) show that the api endpoint is v4 version, based on the document it seems that I also need code field so the current code is not enough now for login?

2. I see you have run the test in CircleCI, but Neither after nor before migrating the CircleCI version from 1.0 to 2.0, I can not make the test_e2e passed and I've notice in login.js, in function login, this.api.perform has never been executed and I don't know why. I've checked some document and I still cannot understand it.

I'm a noob in testing and javascript(I was a Python developer before) and it really frustrates me because I've met a lot of bugs and cannot fix them. I would be appreciate if you could give some suggestion about my two questions.

Thanks,
Junda

**Comment by benjaminheng** [comment]
Hey Junda, I'll take a look at it after work.
